# Site settings
title: Videogames com Cerveja
email: vgscomcerveja@gmail.com
description: >
  Compartilhamos experiências e opiniões gamísticas, tanto ao jogo em si quanto ao seu colecionismo..
  E que adoramos uma cerveja!
baseurl: ""
url: "https://www.vgscomcerveja.com.br"
twitter_username: vgscomcerveja
github_username: felipebbarbosa

enable_disqus: true
enable_analytics: true
enable_googleads: true

# Build settings
markdown: kramdown

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
      og_type: article
      type: article
      excerpt_separator: <!--more-->
      permalink: /post/:title

#files_to_cache:
#  - "/js/vcc.js"

pages_to_cache:
  - "/loja/"
  - "/parceiros/"
  - "/sobre/"
  - "/offline/index.html"

sass:
  style: :compressed

paginate: 7
paginate_path: "page:num"

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME
